### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by joaoescribano** [sunk818/htmlmining#1]
Hey, whats up?

Hope this pool is yours, right? Man, i wish to talk to u :) please contact me on telegram @joaoescribano

Thanks!

**Comment by sunk818** [comment]
The pool does not belong to me. 

There is currently only one mining pool we know of which is run by Alex Ya (Telegram: @Yatson).

He is in the unofficial HTMLCOIN Mining Group
https://t.me/htmlmining

the code for his ccminer that he uses for the pool is here:
https://github.com/yatson1/ccminer-html-cuda

I think he mentioned using your changes to update the ccminer.

thanks again!

**Comment by joaoescribano** [comment]
Nice, i've been banned from this group when i alerted people to do not use (or use at your own risk) closed code blockchain/miner hahahah but its all good! The admin didn't liked..

I've tried to compile it for linux, but no success... I'll create an issue on the repo, thanks!

And I'm really glad it helped somehow the opening of the pool, but im trying to do it opensource to the community, this way we could stabilize the network..

Thanks again for all information!
